name: Unit Tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.2' ]
        wp_version: [ 'latest' ]
        multisite: [ 'false' ]
        object: [ 'false' ]
        include:
          - php: '8.3'
            wp_version: 'trunk'
            object: 'memcached'
            multisite: false
          - php: '8.3'
            wp_version: 'latest'
            object: 'redis'
            multisite: false
          - php: '8.3'
            wp_version: '6.4'
            object: 'false'
            multisite: true
          - php: '7.0'
            wp_version: 'latest'
            object: 'false'
            multisite: false
    uses: alleyinteractive/.github/.github/workflows/php-tests.yml@main
    with:
      multisite: ${{ matrix.multisite }}
      php: ${{ matrix.php }}
      wordpress: ${{ matrix.wp_version }}
      object-cache: ${{ matrix.object }}
      install-core-tests: true
      working-directory: 'plugins/buddypress'
