name: Unit Tests - Object Cache Service

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  tests:
    name: "Object Service ${{ matrix.object }} - WP: ${{ matrix.wp_version }} - PHP: ${{ matrix.php }}"
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']
        wp_version: ['latest']
        multisite: [true, false]
        object: ["memcached", "redis"]

    env:
      WP_INSTALL_CORE_TEST_SUITE: true
      INSTALL_WP_TEST_DEBUG: true
      WP_CORE_DIR: /tmp/wordpress
      WP_MULTISITE: ${{ matrix.multisite == true && 1 || 0 }}

    - name: Install WordPress
      run: |
        bash <(curl -s "https://raw.githubusercontent.com/alleyinteractive/mantle-ci/HEAD/install-wp-tests.sh") wordpress_unit_tests root '' 127.0.0.1 ${{ matrix.wp_version }} false false true

    - name: Running tests
      uses: alleyinteractive/.github/.github/workflows/php-tests.yml@main
      with:
        command: "test"
        dependency-versions: ${{ matrix.dependencies }}
        multisite: ${{ matrix.multisite }}
        php: ${{ matrix.php }}
        wordpress: ${{ matrix.wp_version }}
        object-cache: ${{ matrix.object }}
