name: Unit Tests - Object Cache Service

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  tests:
    name: "Object Service ${{ matrix.object }} - WP: ${{ matrix.wp_version }} - PHP: ${{ matrix.php }}"
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3']
        wp_version: ['latest']
        multisite: [true, false]
        object: ["memcached", "redis"]
    uses: alleyinteractive/.github/.github/workflows/php-tests.yml@feature/php-tests-core-suite
    with:
      multisite: ${{ matrix.multisite }}
      php: ${{ matrix.php }}
      wordpress: ${{ matrix.wp_version }}
      object-cache: ${{ matrix.object }}
      test-suite: 'core-test-suite'
      package-directory: 'plugins/buddypress'
